FROM python:3.6-alpine

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5001
ENV DEBUG true

COPY . /api
WORKDIR /api

# install requirements
# RUN pip install -r requirements.txt

# =========================
# my test uwsgi
RUN apk add gcc libc-dev linux-headers
RUN pip install --upgrade pip
RUN pip install uwsgi
RUN pip install -r requirements.txt
RUN apk del gcc libc-dev linux-headers
# =========================

# expose the app port
EXPOSE 5001

# run the flask development server
# ENTRYPOINT [ "python" ]
# CMD [ "app.py" ]


# =========================
# my test uwsgi
ENTRYPOINT ["uwsgi", "--ini", "/api/uwsgi.ini"]
# =========================
